/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v0.1/auth/dns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange DNS signature for Registry JWT
         * @description Authenticate using DNS TXT record public key and signed timestamp
         */
        post: operations["exchange-dns-token-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/auth/github-at": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange GitHub OAuth access token for Registry JWT
         * @description Exchange a GitHub OAuth access token for a short-lived Registry JWT token
         */
        post: operations["exchange-github-token-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/auth/github-oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange GitHub OIDC token for Registry JWT
         * @description Exchange a GitHub Actions OIDC token for a short-lived Registry JWT token
         */
        post: operations["exchange-github-oidc-token-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/auth/http": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange HTTP signature for Registry JWT
         * @description Authenticate using HTTP-hosted public key and signed timestamp
         */
        post: operations["exchange-http-token-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/auth/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange OIDC ID token for Registry JWT
         * @description Exchange an OIDC ID token from any configured provider for a short-lived Registry JWT token
         */
        post: operations["exchange-oidc-token-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check the health status of the API
         */
        get: operations["get-health-v0.1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Simple ping endpoint
         */
        get: operations["ping-v0.1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish MCP server
         * @description Publish a new MCP server to the registry or update an existing one
         */
        post: operations["publish-server-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List MCP servers
         * @description Get a paginated list of MCP servers from the registry
         */
        get: operations["list-servers-v0.1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/servers/{serverName}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update status for all versions of an MCP server
         * @description Update the status metadata of all versions of an MCP server in a single transaction. Requires publish or edit permission for the server. Either all versions are updated or none on failure.
         */
        patch: operations["update-server-all-versions-status-v0.1"];
        trace?: never;
    };
    "/v0.1/servers/{serverName}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all versions of an MCP server
         * @description Get all available versions for a specific MCP server
         */
        get: operations["get-server-versions-v0.1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/servers/{serverName}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific MCP server version
         * @description Get detailed information about a specific version of an MCP server. Use the special version 'latest' to get the latest version.
         */
        get: operations["get-server-version-v0.1"];
        /**
         * Edit MCP server
         * @description Update the configuration of a specific version of an existing MCP server. Requires edit permission for the server. Use PATCH /servers/{serverName}/versions/{version}/status to update status metadata.
         */
        put: operations["edit-server-v0.1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/servers/{serverName}/versions/{version}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update MCP server status
         * @description Update the status metadata of a specific version of an MCP server. Requires publish or edit permission for the server. This endpoint allows changing status and status message without requiring the full server configuration.
         */
        patch: operations["update-server-status-v0.1"];
        trace?: never;
    };
    "/v0.1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate MCP server JSON
         * @description Validate a server.json file without publishing it to the registry
         */
        post: operations["validate-server-v0.1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0.1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get version information
         * @description Returns the version, git commit, and build time of the registry application
         */
        get: operations["get-version-v0.1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/auth/dns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange DNS signature for Registry JWT
         * @description Authenticate using DNS TXT record public key and signed timestamp
         */
        post: operations["exchange-dns-token-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/auth/github-at": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange GitHub OAuth access token for Registry JWT
         * @description Exchange a GitHub OAuth access token for a short-lived Registry JWT token
         */
        post: operations["exchange-github-token-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/auth/github-oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange GitHub OIDC token for Registry JWT
         * @description Exchange a GitHub Actions OIDC token for a short-lived Registry JWT token
         */
        post: operations["exchange-github-oidc-token-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/auth/http": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange HTTP signature for Registry JWT
         * @description Authenticate using HTTP-hosted public key and signed timestamp
         */
        post: operations["exchange-http-token-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/auth/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange OIDC ID token for Registry JWT
         * @description Exchange an OIDC ID token from any configured provider for a short-lived Registry JWT token
         */
        post: operations["exchange-oidc-token-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check the health status of the API
         */
        get: operations["get-health-v0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Simple ping endpoint
         */
        get: operations["ping-v0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish MCP server
         * @description Publish a new MCP server to the registry or update an existing one
         */
        post: operations["publish-server-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List MCP servers
         * @description Get a paginated list of MCP servers from the registry
         */
        get: operations["list-servers-v0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/servers/{serverName}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update status for all versions of an MCP server
         * @description Update the status metadata of all versions of an MCP server in a single transaction. Requires publish or edit permission for the server. Either all versions are updated or none on failure.
         */
        patch: operations["update-server-all-versions-status-v0"];
        trace?: never;
    };
    "/v0/servers/{serverName}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all versions of an MCP server
         * @description Get all available versions for a specific MCP server
         */
        get: operations["get-server-versions-v0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/servers/{serverName}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get specific MCP server version
         * @description Get detailed information about a specific version of an MCP server. Use the special version 'latest' to get the latest version.
         */
        get: operations["get-server-version-v0"];
        /**
         * Edit MCP server
         * @description Update the configuration of a specific version of an existing MCP server. Requires edit permission for the server. Use PATCH /servers/{serverName}/versions/{version}/status to update status metadata.
         */
        put: operations["edit-server-v0"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/servers/{serverName}/versions/{version}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update MCP server status
         * @description Update the status metadata of a specific version of an MCP server. Requires publish or edit permission for the server. This endpoint allows changing status and status message without requiring the full server configuration.
         */
        patch: operations["update-server-status-v0"];
        trace?: never;
    };
    "/v0/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate MCP server JSON
         * @description Validate a server.json file without publishing it to the registry
         */
        post: operations["validate-server-v0"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get version information
         * @description Returns the version, git commit, and build time of the registry application
         */
        get: operations["get-version-v0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Argument: {
            /** @description A list of possible values for the input. If provided, the user must select one of these values. */
            choices?: string[] | null;
            /** @description The default value for the input. This should be a valid value for the input. If you want to provide input examples or guidance, use the placeholder field instead. */
            default?: string;
            /** @description A description of the input, which clients can use to provide context to the user. */
            description?: string;
            /**
             * @description Specifies the input format. Supported values include filepath, which should be interpreted as a file on the user's filesystem.
             * @enum {string}
             */
            format?: "string" | "number" | "boolean" | "filepath";
            /** @description Whether the argument can be repeated multiple times. */
            isRepeated?: boolean;
            /** @description Whether the input is required */
            isRequired?: boolean;
            /** @description Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely. */
            isSecret?: boolean;
            /**
             * @description The flag name (for named arguments), including any leading dashes. Empty for positional arguments.
             * @example --port
             */
            name?: string;
            /** @description A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input. */
            placeholder?: string;
            /**
             * @description Argument type: 'positional' or 'named'
             * @example positional
             */
            type: string;
            /** @description The value for the input. If this is not set, the user may be prompted to provide a value. Identifiers wrapped in {curly_braces} will be replaced with the corresponding properties from the input variables map. */
            value?: string;
            /**
             * @description An identifier for positional arguments. Used in transport URL variable substitution.
             * @example file_path
             */
            valueHint?: string;
            /** @description A map of variable names to their values. Keys in the input value that are wrapped in {curly_braces} will be replaced with the corresponding variable values. */
            variables?: {
                [key: string]: components["schemas"]["Input"];
            };
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GitHubOIDCTokenExchangeInputBody: {
            /** @description GitHub Actions OIDC token */
            oidc_token: string;
        };
        GitHubTokenExchangeInputBody: {
            /** @description GitHub OAuth token */
            github_token: string;
        };
        HealthBody: {
            /** @description GitHub OAuth App Client ID */
            github_client_id?: string;
            /**
             * @description Health status
             * @example ok
             */
            status: string;
        };
        Icon: {
            /**
             * @description Optional MIME type override if the source MIME type is missing or generic. Must be one of: image/png, image/jpeg, image/jpg, image/svg+xml, image/webp.
             * @example image/png
             * @enum {string}
             */
            mimeType?: "image/png" | "image/jpeg" | "image/jpg" | "image/svg+xml" | "image/webp";
            /** @description Optional array of strings that specify sizes at which the icon can be used. Each string should be in WxH format (e.g., '48x48', '96x96') or 'any' for scalable formats like SVG. If not provided, the client should assume that the icon can be used at any size. */
            sizes?: string[] | null;
            /**
             * Format: uri
             * @description A standard URI pointing to an icon resource. Must be an HTTPS URL. Consumers SHOULD take steps to ensure URLs serving icons are from the same domain as the server or a trusted domain. Consumers SHOULD take appropriate precautions when consuming SVGs as they can contain executable JavaScript.
             * @example https://example.com/icon.png
             */
            src: string;
            /**
             * @description Optional specifier for the theme this icon is designed for. 'light' indicates the icon is designed to be used with a light background, and 'dark' indicates the icon is designed to be used with a dark background. If not provided, the client should assume the icon can be used with any theme.
             * @enum {string}
             */
            theme?: "light" | "dark";
        };
        Input: {
            /** @description A list of possible values for the input. If provided, the user must select one of these values. */
            choices?: string[] | null;
            /** @description The default value for the input. This should be a valid value for the input. If you want to provide input examples or guidance, use the placeholder field instead. */
            default?: string;
            /** @description A description of the input, which clients can use to provide context to the user. */
            description?: string;
            /**
             * @description Specifies the input format. Supported values include filepath, which should be interpreted as a file on the user's filesystem.
             * @enum {string}
             */
            format?: "string" | "number" | "boolean" | "filepath";
            /** @description Whether the input is required */
            isRequired?: boolean;
            /** @description Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely. */
            isSecret?: boolean;
            /** @description A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input. */
            placeholder?: string;
            /** @description The value for the input. If this is not set, the user may be prompted to provide a value. Identifiers wrapped in {curly_braces} will be replaced with the corresponding properties from the input variables map. */
            value?: string;
        };
        KeyValueInput: {
            /** @description A list of possible values for the input. If provided, the user must select one of these values. */
            choices?: string[] | null;
            /** @description The default value for the input. This should be a valid value for the input. If you want to provide input examples or guidance, use the placeholder field instead. */
            default?: string;
            /** @description A description of the input, which clients can use to provide context to the user. */
            description?: string;
            /**
             * @description Specifies the input format. Supported values include filepath, which should be interpreted as a file on the user's filesystem.
             * @enum {string}
             */
            format?: "string" | "number" | "boolean" | "filepath";
            /** @description Whether the input is required */
            isRequired?: boolean;
            /** @description Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely. */
            isSecret?: boolean;
            /**
             * @description Name of the header or environment variable.
             * @example SOME_VARIABLE
             */
            name: string;
            /** @description A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input. */
            placeholder?: string;
            /** @description The value for the input. If this is not set, the user may be prompted to provide a value. Identifiers wrapped in {curly_braces} will be replaced with the corresponding properties from the input variables map. */
            value?: string;
            /** @description A map of variable names to their values. Keys in the input value that are wrapped in {curly_braces} will be replaced with the corresponding variable values. */
            variables?: {
                [key: string]: components["schemas"]["Input"];
            };
        };
        Metadata: {
            /**
             * Format: int64
             * @description Number of items in current page
             */
            count: number;
            /** @description Pagination cursor for retrieving the next page of results. Use this exact value in the cursor query parameter of your next request. */
            nextCursor?: string;
        };
        OIDCTokenExchangeInputBody: {
            /** @description OIDC ID token from any provider */
            oidc_token: string;
        };
        Package: {
            /** @description A mapping of environment variables to be set when running the package. */
            environmentVariables?: components["schemas"]["KeyValueInput"][] | null;
            /**
             * @description SHA-256 hash of the package file for integrity verification. Required for MCPB packages and optional for other package types. Authors are responsible for generating correct SHA-256 hashes when creating server.json. If present, MCP clients must validate the downloaded file matches the hash before running packages to ensure file integrity.
             * @example fe333e598595000ae021bd27117db32ec69af6987f507ba7a63c90638ff633ce
             */
            fileSha256?: string;
            /**
             * @description Package identifier - either a package name (for registries) or URL (for direct downloads)
             * @example @modelcontextprotocol/server-brave-search
             */
            identifier: string;
            /** @description A list of arguments to be passed to the package's binary. */
            packageArguments?: components["schemas"]["Argument"][] | null;
            /**
             * Format: uri
             * @description Base URL of the package registry
             * @example https://registry.npmjs.org
             */
            registryBaseUrl?: string;
            /**
             * @description Registry type indicating how to download packages (e.g., 'npm', 'pypi', 'oci', 'nuget', 'mcpb')
             * @example npm
             */
            registryType: string;
            /** @description A list of arguments to be passed to the package's runtime command (such as docker or npx). The runtimeHint field should be provided when runtimeArguments are present. */
            runtimeArguments?: components["schemas"]["Argument"][] | null;
            /**
             * @description A hint to help clients determine the appropriate runtime for the package. This field should be provided when runtimeArguments are present.
             * @example npx
             */
            runtimeHint?: string;
            /** @description Transport protocol configuration for the package */
            transport: components["schemas"]["Transport"];
            /**
             * @description Package version. Must be a specific version. Version ranges are rejected (e.g., '^1.2.3', '~1.2.3', '>=1.2.3', '1.x', '1.*').
             * @example 1.0.2
             */
            version?: string;
        };
        PingBody: {
            /**
             * @description Ping response
             * @example true
             */
            pong: boolean;
        };
        RegistryExtensions: {
            /** @description Whether this is the latest version of the server */
            isLatest: boolean;
            /**
             * Format: date-time
             * @description Timestamp when the server was first published to the registry
             */
            publishedAt: string;
            /**
             * @description Server lifecycle status
             * @enum {string}
             */
            status: "active" | "deprecated" | "deleted";
            /**
             * Format: date-time
             * @description Timestamp when the server status was last changed
             */
            statusChangedAt: string;
            /** @description Optional message explaining status change (e.g., deprecation reason, migration guidance) */
            statusMessage?: string;
            /**
             * Format: date-time
             * @description Timestamp when the server entry was last updated
             */
            updatedAt?: string;
        };
        Repository: {
            /**
             * @description Repository identifier from the hosting service (e.g., GitHub repo ID). Owned and determined by the source forge. Should remain stable across repository renames and may be used to detect repository resurrection attacks - if a repository is deleted and recreated, the ID should change. For GitHub, use: gh api repos/<owner>/<repo> --jq '.id'
             * @example b94b5f7e-c7c6-d760-2c78-a5e9b8a5b8c9
             */
            id?: string;
            /**
             * @description Repository hosting service identifier. Used by registries to determine validation and API access methods.
             * @example github
             */
            source?: string;
            /**
             * @description Optional relative path from repository root to the server location within a monorepo or nested package structure. Must be a clean relative path.
             * @example src/everything
             */
            subfolder?: string;
            /**
             * Format: uri
             * @description Repository URL for browsing source code. Should support both web browsing and git clone operations.
             * @example https://github.com/modelcontextprotocol/servers
             */
            url?: string;
        };
        ResponseMeta: {
            /** @description Official MCP registry metadata */
            "io.modelcontextprotocol.registry/official"?: components["schemas"]["RegistryExtensions"];
        };
        ServerJSON: {
            /**
             * Format: uri
             * @description JSON Schema URI for this server.json format
             * @example https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json
             */
            $schema: string;
            /** @description Extension metadata using reverse DNS namespacing for vendor-specific data */
            _meta?: components["schemas"]["ServerMeta"];
            /**
             * @description Clear human-readable explanation of server functionality.
             * @example MCP server providing weather data and forecasts via OpenWeatherMap API
             */
            description: string;
            /** @description Optional set of sized icons that the client can display in a user interface. */
            icons?: components["schemas"]["Icon"][] | null;
            /**
             * @description Server name in reverse-DNS format. Must contain exactly one forward slash separating namespace from server name.
             * @example io.github.user/weather
             */
            name: string;
            /** @description Array of package configurations */
            packages?: components["schemas"]["Package"][] | null;
            /** @description Array of remote configurations */
            remotes?: components["schemas"]["Transport"][] | null;
            /** @description Optional repository metadata for the MCP server source code. */
            repository?: components["schemas"]["Repository"];
            /**
             * @description Optional human-readable title or display name for the MCP server.
             * @example Weather API
             */
            title?: string;
            /**
             * @description Version string for this server. SHOULD follow semantic versioning.
             * @example 1.0.2
             */
            version: string;
            /**
             * Format: uri
             * @description Optional URL to the server's homepage, documentation, or project website.
             * @example https://modelcontextprotocol.io/examples
             */
            websiteUrl?: string;
        };
        ServerListResponse: {
            /** @description Pagination metadata */
            metadata: components["schemas"]["Metadata"];
            /** @description List of server entries */
            servers: components["schemas"]["ServerResponse"][] | null;
        };
        ServerMeta: {
            /** @description Publisher-provided metadata for downstream registries */
            "io.modelcontextprotocol.registry/publisher-provided"?: {
                [key: string]: unknown;
            };
        };
        ServerResponse: {
            /** @description Registry-managed metadata */
            _meta: components["schemas"]["ResponseMeta"];
            /** @description Server configuration and metadata */
            server: components["schemas"]["ServerJSON"];
        };
        SignatureTokenExchangeInput: {
            /**
             * @description Domain name
             * @example example.com
             */
            domain: string;
            /**
             * @description Hex-encoded signature of timestamp
             * @example abcdef1234567890
             */
            signed_timestamp: string;
            /**
             * @description RFC3339 timestamp
             * @example 2023-01-01T00:00:00Z
             */
            timestamp: string;
        };
        TokenResponse: {
            /** Format: int64 */
            expires_at: number;
            registry_token: string;
        };
        Transport: {
            /** @description HTTP headers for streamable-http or sse transports */
            headers?: components["schemas"]["KeyValueInput"][] | null;
            /**
             * @description Transport type (stdio, streamable-http, or sse)
             * @example stdio
             */
            type: string;
            /**
             * @description URL for streamable-http or sse transports
             * @example https://api.example.com/mcp
             */
            url?: string;
            /** @description Variables for URL templating in remote transports */
            variables?: {
                [key: string]: components["schemas"]["Input"];
            };
        };
        UpdateAllVersionsStatusResponse: {
            /** @description List of all updated server versions */
            servers: components["schemas"]["ServerResponse"][] | null;
            /**
             * Format: int64
             * @description Number of versions updated
             */
            updatedCount: number;
        };
        UpdateServerStatusBody: {
            /**
             * @description New server lifecycle status
             * @enum {string}
             */
            status: "active" | "deprecated" | "deleted";
            /** @description Optional message explaining the status change (e.g., reason for deprecation) */
            statusMessage?: string;
        };
        ValidationIssue: {
            message: string;
            path: string;
            reference: string;
            severity: string;
            type: string;
        };
        ValidationResult: {
            issues: components["schemas"]["ValidationIssue"][] | null;
            valid: boolean;
        };
        VersionBody: {
            /**
             * @description Build timestamp
             * @example 2025-10-14T12:00:00Z
             */
            build_time: string;
            /**
             * @description Git commit SHA
             * @example abc123d
             */
            git_commit: string;
            /**
             * @description Application version
             * @example v1.0.0
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Argument = components['schemas']['Argument'];
export type ErrorDetail = components['schemas']['ErrorDetail'];
export type ErrorModel = components['schemas']['ErrorModel'];
export type GitHubOidcTokenExchangeInputBody = components['schemas']['GitHubOIDCTokenExchangeInputBody'];
export type GitHubTokenExchangeInputBody = components['schemas']['GitHubTokenExchangeInputBody'];
export type HealthBody = components['schemas']['HealthBody'];
export type Icon = components['schemas']['Icon'];
export type Input = components['schemas']['Input'];
export type KeyValueInput = components['schemas']['KeyValueInput'];
export type Metadata = components['schemas']['Metadata'];
export type OidcTokenExchangeInputBody = components['schemas']['OIDCTokenExchangeInputBody'];
export type Package = components['schemas']['Package'];
export type PingBody = components['schemas']['PingBody'];
export type RegistryExtensions = components['schemas']['RegistryExtensions'];
export type Repository = components['schemas']['Repository'];
export type ResponseMeta = components['schemas']['ResponseMeta'];
export type ServerJson = components['schemas']['ServerJSON'];
export type ServerListResponse = components['schemas']['ServerListResponse'];
export type ServerMeta = components['schemas']['ServerMeta'];
export type ServerResponse = components['schemas']['ServerResponse'];
export type SignatureTokenExchangeInput = components['schemas']['SignatureTokenExchangeInput'];
export type TokenResponse = components['schemas']['TokenResponse'];
export type Transport = components['schemas']['Transport'];
export type UpdateAllVersionsStatusResponse = components['schemas']['UpdateAllVersionsStatusResponse'];
export type UpdateServerStatusBody = components['schemas']['UpdateServerStatusBody'];
export type ValidationIssue = components['schemas']['ValidationIssue'];
export type ValidationResult = components['schemas']['ValidationResult'];
export type VersionBody = components['schemas']['VersionBody'];
export type $defs = Record<string, never>;
export interface operations {
    "exchange-dns-token-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignatureTokenExchangeInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-github-token-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubTokenExchangeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-github-oidc-token-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubOIDCTokenExchangeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-http-token-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignatureTokenExchangeInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-oidc-token-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCTokenExchangeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-health-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ping-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "publish-server-v0.1": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token (obtained from /v0/auth/token/github) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerJSON"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-servers-v0.1": {
        parameters: {
            query?: {
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter servers updated since timestamp (RFC3339 datetime) */
                updated_since?: string;
                /** @description Search servers by name (substring match) */
                search?: string;
                /** @description Filter by version ('latest' for latest version, or an exact version like '1.2.3') */
                version?: string;
                /** @description Include deleted servers in results (default: false, but always true when updated_since is provided) */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-server-all-versions-status-v0.1": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token with publish or edit permissions */
                Authorization: string;
            };
            path: {
                /** @description URL-encoded server name */
                serverName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerStatusBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateAllVersionsStatusResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-server-versions-v0.1": {
        parameters: {
            query?: {
                /** @description Include deleted servers in results (default: false) */
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                /** @description URL-encoded server name */
                serverName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-server-version-v0.1": {
        parameters: {
            query?: {
                /** @description Include deleted servers in results (default: false) */
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                /** @description URL-encoded server name */
                serverName: string;
                /** @description URL-encoded server version */
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "edit-server-v0.1": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token with edit permissions */
                Authorization: string;
            };
            path: {
                /** @description URL-encoded server name */
                serverName: string;
                /** @description URL-encoded version to edit */
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerJSON"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-server-status-v0.1": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token with publish or edit permissions */
                Authorization: string;
            };
            path: {
                /** @description URL-encoded server name */
                serverName: string;
                /** @description URL-encoded version to update */
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerStatusBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "validate-server-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerJSON"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-version-v0.1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-dns-token-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignatureTokenExchangeInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-github-token-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubTokenExchangeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-github-oidc-token-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubOIDCTokenExchangeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-http-token-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignatureTokenExchangeInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "exchange-oidc-token-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCTokenExchangeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-health-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ping-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "publish-server-v0": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token (obtained from /v0/auth/token/github) */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerJSON"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-servers-v0": {
        parameters: {
            query?: {
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter servers updated since timestamp (RFC3339 datetime) */
                updated_since?: string;
                /** @description Search servers by name (substring match) */
                search?: string;
                /** @description Filter by version ('latest' for latest version, or an exact version like '1.2.3') */
                version?: string;
                /** @description Include deleted servers in results (default: false, but always true when updated_since is provided) */
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-server-all-versions-status-v0": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token with publish or edit permissions */
                Authorization: string;
            };
            path: {
                /** @description URL-encoded server name */
                serverName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerStatusBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateAllVersionsStatusResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-server-versions-v0": {
        parameters: {
            query?: {
                /** @description Include deleted servers in results (default: false) */
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                /** @description URL-encoded server name */
                serverName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerListResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-server-version-v0": {
        parameters: {
            query?: {
                /** @description Include deleted servers in results (default: false) */
                include_deleted?: boolean;
            };
            header?: never;
            path: {
                /** @description URL-encoded server name */
                serverName: string;
                /** @description URL-encoded server version */
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "edit-server-v0": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token with edit permissions */
                Authorization: string;
            };
            path: {
                /** @description URL-encoded server name */
                serverName: string;
                /** @description URL-encoded version to edit */
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerJSON"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-server-status-v0": {
        parameters: {
            query?: never;
            header: {
                /** @description Registry JWT token with publish or edit permissions */
                Authorization: string;
            };
            path: {
                /** @description URL-encoded server name */
                serverName: string;
                /** @description URL-encoded version to update */
                version: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServerStatusBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "validate-server-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerJSON"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-version-v0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
